modLoader="javafml"
loaderVersion="[46,)"
license="MIT"
[[mods]]
modId="charm_core"
version="${version}"
displayName="Charm core"
credits=""
authors="svenhjol"
description='''
Charm core.
'''
logoFile="icon.png"
[[dependencies.charm_core]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.charm_core]]
    modId="charm_api"
    mandatory=true
    versionRange="[5.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.charm_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"
